/**
 * @file Request Status Constant
 * @description Logic for Request Status Constant
 */

// Section: Logic
export const REQUEST_STATUS = {
    NEW: 'NEW',
    VERIFIED: 'VERIFIED',
    WAITING_CHECK: 'WAITING_CHECK',
    PENDING_ACTION: 'PENDING_ACTION',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    REFERRED_BACK: 'REFERRED_BACK'
};

export const REQUEST_STATUS_LABEL: Record<string, string> = {
    [REQUEST_STATUS.NEW]: 'คำขอใหม่',
    [REQUEST_STATUS.VERIFIED]: 'ตรวจสอบแล้ว',
    [REQUEST_STATUS.WAITING_CHECK]: 'รอตรวจสอบ',
    [REQUEST_STATUS.PENDING_ACTION]: 'รอดำเนินการ',
    [REQUEST_STATUS.PENDING_APPROVAL]: 'อยู่ระหว่างการอนุมัติ',
    [REQUEST_STATUS.APPROVED]: 'อนุมัติแล้ว',
    [REQUEST_STATUS.REJECTED]: 'ไม่อนุมัติ',
    [REQUEST_STATUS.REFERRED_BACK]: 'รอแก้ไข'
};

export const REQUEST_STATUS_LIST = [
    REQUEST_STATUS.NEW,
    REQUEST_STATUS.WAITING_CHECK,
    REQUEST_STATUS.PENDING_APPROVAL,
    REQUEST_STATUS.APPROVED
];

export const COMMON_STATUS_OPTIONS = [
    { value: REQUEST_STATUS.NEW, label: REQUEST_STATUS_LABEL[REQUEST_STATUS.NEW] },
    { value: REQUEST_STATUS.WAITING_CHECK, label: REQUEST_STATUS_LABEL[REQUEST_STATUS.WAITING_CHECK] },
    { value: REQUEST_STATUS.PENDING_APPROVAL, label: REQUEST_STATUS_LABEL[REQUEST_STATUS.PENDING_APPROVAL] },
    { value: REQUEST_STATUS.APPROVED, label: REQUEST_STATUS_LABEL[REQUEST_STATUS.APPROVED] }
];
