import { Employee } from "../pages/resign-management/employeeData.interface";

export const MOCK_EMPLOYEES: Employee[] = [
    {
        empCode: 'OTD0001',
        firstName: 'ปัณณพร',
        lastName: 'จึงเปี่ยมสุข',
        firstNameEng: 'Punaporn',
        lastNameEng: 'Jungpeamsook',
        nickName: 'เพียว',
        department: 'IT',
        company: 'OTD',
        type: 'FullTime',
        adUser: 'punaporn.j',
    },
    {
        empCode: 'OTD0002',
        firstName: 'ธราดล',
        lastName: 'แก้วนาน',
        firstNameEng: 'Tharadl',
        lastNameEng: 'Kaewnan',
        nickName: 'โด้',
        department: 'Infrastructure',
        company: 'OTD',
        type: 'Contract',
        adUser: 'tharadl.g',
    },
    {
        empCode: 'OTD0003',
        firstName: 'อรทัย',
        lastName: 'บัวศรี',
        firstNameEng: 'Ortai',
        lastNameEng: 'Bua Sri',
        nickName: 'อ๊อฟ',
        department: 'Finance',
        company: 'OTD',
        type: 'Freelance',
        adUser: 'ortai.b',
    },
    {
        empCode: 'OTD0004',
        firstName: 'สุทัศน์',
        lastName: 'ยาละ',
        firstNameEng: 'Sutas',
        lastNameEng: 'Yala',
        nickName: 'ต้น',
        department: 'HR',
        company: 'OTD',
        type: 'FullTime',
        adUser: 'sutas.y',
    },
    {
        empCode: 'OTD0005',
        firstName: 'กิตติพงศ์',
        lastName: 'ทองดี',
        firstNameEng: 'Kittipong',
        lastNameEng: 'Thongdee',
        nickName: 'ก้อง',
        department: 'IT',
        company: 'OTD',
        type: 'FullTime',
        adUser: 'kittipong.t',
    },
    {
        empCode: 'OTD0006',
        firstName: 'พัชราภา',
        lastName: 'ศรีสวัสดิ์',
        firstNameEng: 'Patcharapa',
        lastNameEng: 'Srisawat',
        nickName: 'แพร',
        department: 'Marketing',
        company: 'OTD',
        type: 'Freelance',
        adUser: 'patcharapa.s',
    },
    {
        empCode: 'OTD0007',
        firstName: 'ณัฐวุฒิ',
        lastName: 'ชัยมงคล',
        firstNameEng: 'Nattawut',
        lastNameEng: 'Chaimongkol',
        nickName: 'นัท',
        department: 'Support',
        company: 'OTD',
        type: 'Contract',
        adUser: 'nattawut.c',
    },
    {
        empCode: 'OTD0008',
        firstName: 'ศศิธร',
        lastName: 'อินทร์แก้ว',
        firstNameEng: 'Sasithorn',
        lastNameEng: 'Inkaew',
        nickName: 'ฝน',
        department: 'HR',
        company: 'OTD',
        type: 'FullTime',
        adUser: 'sasithorn.i',
    },
    {
        empCode: 'OTD0009',
        firstName: 'ภานุวัฒน์',
        lastName: 'รุ่งเรือง',
        firstNameEng: 'Phanuwat',
        lastNameEng: 'Rungrueang',
        nickName: 'บอย',
        department: 'Finance',
        company: 'OTD',
        type: 'FullTime',
        adUser: 'phanuwat.r',
    },
    {
        empCode: 'OTD0010',
        firstName: 'วริศรา',
        lastName: 'บุญมี',
        firstNameEng: 'Warissara',
        lastNameEng: 'Boonmee',
        nickName: 'มิ้น',
        department: 'IT',
        company: 'OTD',
        type: 'Freelance',
        adUser: 'warissara.b',
    },
];
